version: '3'
services:
  app:
    platform: linux/x86_64
    container_name: app
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'transaction-api-mongodb'
    env_file: ./containerConfig/mongodb.env
    ports:
      - '27017:27017'
    volumes:
      - ./containerConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./.data/mongdb:/data/db